name: cpray_gaming
description: "A modern low-latency VPN and gaming tunnel desktop client for Windows."
publish_to: 'none'
version: 0.0.5+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  window_manager: ^0.3.9
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
